name: GitHub Achievements

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  achievements:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Trophy
        uses: ryosukeijima/github-profile-trophy@v1
        with:
          username: yousufansari-dev
