name: GitHub Cards & Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Refresh GitHub Stats
        run: echo "GitHub stats cards refreshed"
