name: Update GitHub Cards

on:
  schedule:
    - cron: "0 2 * * *" # Daily at 2 AM
  workflow_dispatch:

jobs:
  generate-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Generate GitHub Stats Card
        run: |
          curl -o dist/github-stats.svg "https://github-readme-stats.vercel.app/api?username=yousufansari-dev&show_icons=true&theme=radical&hide_border=false&count_private=true&hide_title=false"
          curl -o dist/github-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=yousufansari-dev&layout=compact&theme=radical&hide_border=false&langs_count=10"
          curl -o dist/github-wakatime.svg "https://github-readme-stats.vercel.app/api/wakatime?username=yousufansari-dev&theme=radical&hide_border=false"

      - name: Deploy to Output Branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
